Added redis Sorted Sets and Scripting (module a few things and tests)
ktorio/ktor-clients pull request #3
Opened 2018-07-25 10:55 UTC by soywiz

2018-07-26 05:03 UTC, e5l commented
Hi, @soywiz. Thanks for the PR. How'd you think, could we try to use the Ktor `TypeInfo` and reified inline to replace command methods with a single one?

2018-07-27 07:24 UTC, e5l requested changes

2018-07-27 07:24 UTC, e5l commented on src/io/ktor/experimental/client/redis/RedisCommands.kt
> +suspend fun Redis.commandArrayStringNotNull(vararg args: Any?): List<String> =
Could we merge it with commandArrayString? or maybe try to extract difference.
At least we could think about naming

2018-07-27 07:24 UTC, e5l commented on src/io/ktor/experimental/client/redis/RedisCommands.kt
> +    (0 until size / 2).map { ("" + this[it * 2 + 0]) to ("" + this[it * 2 + 1]) }
Consider to avoid `"" + something` conversions. I'd prefer a more explicit way to do it.

2018-07-27 07:24 UTC, e5l commented on src/io/ktor/experimental/client/redis/RedisCommandsScripting.kt
> +    return execute(
Probably can be an expression body

2018-07-27 07:24 UTC, e5l commented on src/io/ktor/experimental/client/redis/RedisCommandsScripting.kt
> +suspend fun Redis.scriptLoad(script: String): String = this.commandString("SCRIPT", "LOAD", script) ?: ""
Let's extract script methods to separate file

2018-07-27 07:24 UTC, e5l commented on src/io/ktor/experimental/client/redis/RedisCommandsSortedSets.kt
> +suspend fun Redis.bzpopmax(vararg keys: String, timeout: Long = 0): List<String> = TODO()
Please consider making `TODO` methods internal.

2018-07-31 14:27 UTC, soywiz commented
Fixed most of the things you requested. Except moving the script part to another file. It was already in its own file.

Regarding to use reified and TypeInfo. I'm not sure how to provide a single method not using reflection, not adding additional overhead and supporting default values. If you know a way to do that, that would be super great. Let me know if you change it so I can take note for other projects :)

2018-07-31 14:28 UTC, soywiz commented on src/io/ktor/experimental/client/redis/RedisCommandsScripting.kt
> +suspend fun Redis.scriptLoad(script: String): String = this.commandString("SCRIPT", "LOAD", script) ?: ""
It is in `RedisCommandsScripting.kt`. Check this page: https://redis.io/commands#scripting
I'm grouping commands based on the official dropdown of categories/groups. SCRIPT and EVAL work together as part of the LUA scripting support in Redis.

2018-08-01 08:27 UTC, e5l approved these changes

2018-08-01 08:27 UTC, merged